title: Aksh Shah
logo: /Profile_Pic/Image.jpeg
description: Data Analyst
show_downloads: true
theme: jekyll-theme-minimal
github_username: Aksh830
linkedin_username: in/akshshah666
email: akshshah666@gmail.com

